/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchRecord: typeof import('./../src/components/search/record.vue')['default']
    SearchSearchContent: typeof import('./../src/components/search/search-content.vue')['default']
    VftAvatar: typeof import('vft/es')['VftAvatar']
    VftBackTop: typeof import('vft/es')['VftBackTop']
    VftConfigProvider: typeof import('vft/es')['VftConfigProvider']
    VftEmpty: typeof import('vft/es')['VftEmpty']
    VftFooterLayout: typeof import('vft/es')['VftFooterLayout']
    VftFullScreen: typeof import('vft/es')['VftFullScreen']
    VftHeaderLayout: typeof import('vft/es')['VftHeaderLayout']
    VftIcon: typeof import('vft/es')['VftIcon']
    VftIconText: typeof import('vft/es')['VftIconText']
    VftIframeLayout: typeof import('vft/es')['VftIframeLayout']
    VftLink: typeof import('vft/es')['VftLink']
    VftMdContainer: typeof import('vft/es')['VftMdContainer']
    VftMenu: typeof import('vft/es')['VftMenu']
    VftMenuItem: typeof import('vft/es')['VftMenuItem']
    VftMultipleTabs: typeof import('vft/es')['VftMultipleTabs']
    VftOverlay: typeof import('vft/es')['VftOverlay']
    VftPagination: typeof import('vft/es')['VftPagination']
    VftPopover: typeof import('vft/es')['VftPopover']
    VftRouterViewContent: typeof import('vft/es')['VftRouterViewContent']
    VftSearch: typeof import('vft/es')['VftSearch']
    VftSideMenu: typeof import('vft/es')['VftSideMenu']
    VftSubMenu: typeof import('vft/es')['VftSubMenu']
    VftTag: typeof import('vft/es')['VftTag']
  }
}
